import React, { Component } from 'react';
import { connect } from 'react-redux';
import { SHr, SIcon, SNavigation, SPage, SText, STheme, SView } from 'servisofts-component';
import { MenuButtom, MenuPages } from 'servisofts-rn-roles_permisos';
import MensajesLista from './Components/MensajesLista';
import MensajeDetalle from './Components/MensajeDetalle';
import MensajeContacto from './Components/MensajeContacto';
import MDL from '../../MDL';
class mensajes extends Component {
    constructor(props) {
        super(props);
        this.state = {
            data: [
                {
                    "id": {
                        "server": "c.us",
                        "user": "59173138212",
                        "_serialized": "59173138212@c.us"
                    },
                    "messages": [
                        {
                            "_data": {
                                "id": {
                                    "fromMe": true,
                                    "remote": "59175666929@c.us",
                                    "id": "8F53DF7A566250AAD5",
                                    "_serialized": "true_59175666929@c.us_8F53DF7A566250AAD5"
                                },
                                "rowId": 999999985,
                                "viewed": false,
                                "body": "Hola Ruddy",
                                "type": "chat",
                                "t": 1758337103,
                                "from": {
                                    "server": "c.us",
                                    "user": "59178505744",
                                    "_serialized": "59178505744@c.us"
                                },
                                "to": {
                                    "server": "c.us",
                                    "user": "59175666929",
                                    "_serialized": "59175666929@c.us"
                                },
                                "ack": 3,
                                "invis": true,
                                "star": false,
                                "kicNotified": false,
                                "isFromTemplate": false,
                                "pollOptions": [],
                                "pollInvalidated": false,
                                "pollVotesSnapshot": {
                                    "pollVotes": []
                                },
                                "latestEditMsgKey": null,
                                "latestEditSenderTimestampMs": null,
                                "mentionedJidList": [],
                                "groupMentions": [],
                                "eventInvalidated": false,
                                "isVcardOverMmsDocument": false,
                                "isForwarded": false,
                                "isQuestion": false,
                                "questionReplyQuotedMessage": null,
                                "questionResponsesCount": 0,
                                "readQuestionResponsesCount": 0,
                                "labels": [],
                                "hasReaction": false,
                                "viewMode": "VISIBLE",
                                "originalSelfAuthor": {
                                    "server": "c.us",
                                    "user": "59178505744",
                                    "_serialized": "59178505744@c.us"
                                },
                                "productHeaderImageRejected": false,
                                "lastPlaybackProgress": 0,
                                "isDynamicReplyButtonsMsg": false,
                                "isCarouselCard": false,
                                "parentMsgId": null,
                                "callSilenceReason": null,
                                "isVideoCall": false,
                                "callDuration": null,
                                "callCreator": null,
                                "callParticipants": null,
                                "isCallLink": null,
                                "callLinkToken": null,
                                "isMdHistoryMsg": true,
                                "stickerSentTs": 0,
                                "isAvatar": false,
                                "lastUpdateFromServerTs": 0,
                                "invokedBotWid": null,
                                "botTargetSenderJid": null,
                                "bizBotType": null,
                                "botResponseTargetId": null,
                                "botPluginType": null,
                                "botPluginReferenceIndex": null,
                                "botPluginSearchProvider": null,
                                "botPluginSearchUrl": null,
                                "botPluginSearchQuery": null,
                                "botPluginMaybeParent": false,
                                "botReelPluginThumbnailCdnUrl": null,
                                "botMessageDisclaimerText": null,
                                "botMsgBodyType": null,
                                "requiresDirectConnection": false,
                                "bizContentPlaceholderType": null,
                                "hostedBizEncStateMismatch": false,
                                "senderOrRecipientAccountTypeHosted": false,
                                "placeholderCreatedWhenAccountIsHosted": false,
                                "galaxyFlowDisabled": false,
                                "links": []
                            },
                            "id": {
                                "fromMe": true,
                                "remote": "59175666929@c.us",
                                "id": "8F53DF7A566250AAD5",
                                "_serialized": "true_59175666929@c.us_8F53DF7A566250AAD5"
                            },
                            "ack": 3,
                            "hasMedia": false,
                            "body": "Hola Ruddy",
                            "type": "chat",
                            "timestamp": 1758337103,
                            "from": "59178505744@c.us",
                            "to": "59175666929@c.us",
                            "deviceType": "web",
                            "isForwarded": false,
                            "forwardingScore": 0,
                            "isStatus": false,
                            "isStarred": false,
                            "fromMe": true,
                            "hasQuotedMsg": false,
                            "hasReaction": false,
                            "vCards": [],
                            "mentionedIds": [],
                            "groupMentions": [],
                            "isGif": false,
                            "links": []
                        },
                        {
                            "_data": {
                                "id": {
                                    "fromMe": false,
                                    "remote": "59175666929@c.us",
                                    "id": "3A4E4A02958D133D7D41",
                                    "_serialized": "false_59175666929@c.us_3A4E4A02958D133D7D41"
                                },
                                "viewed": false,
                                "body": "Que tal",
                                "type": "chat",
                                "t": 1758337123,
                                "notifyName": "",
                                "from": {
                                    "server": "c.us",
                                    "user": "59175666929",
                                    "_serialized": "59175666929@c.us"
                                },
                                "to": {
                                    "server": "c.us",
                                    "user": "59178505744",
                                    "_serialized": "59178505744@c.us"
                                },
                                "ack": 0,
                                "invis": false,
                                "star": false,
                                "kicNotified": false,
                                "isFromTemplate": false,
                                "pollInvalidated": false,
                                "isSentCagPollCreation": false,
                                "latestEditMsgKey": null,
                                "latestEditSenderTimestampMs": null,
                                "broadcast": false,
                                "mentionedJidList": [],
                                "groupMentions": [],
                                "isEventCanceled": false,
                                "eventInvalidated": false,
                                "isVcardOverMmsDocument": false,
                                "isForwarded": false,
                                "isQuestion": false,
                                "questionReplyQuotedMessage": null,
                                "questionResponsesCount": 0,
                                "readQuestionResponsesCount": 0,
                                "labels": [],
                                "hasReaction": false,
                                "viewMode": "VISIBLE",
                                "messageSecret": {
                                    "0": 38,
                                    "1": 137,
                                    "2": 91,
                                    "3": 107,
                                    "4": 77,
                                    "5": 80,
                                    "6": 174,
                                    "7": 161,
                                    "8": 41,
                                    "9": 180,
                                    "10": 147,
                                    "11": 32,
                                    "12": 187,
                                    "13": 143,
                                    "14": 7,
                                    "15": 191,
                                    "16": 243,
                                    "17": 107,
                                    "18": 45,
                                    "19": 47,
                                    "20": 144,
                                    "21": 233,
                                    "22": 231,
                                    "23": 46,
                                    "24": 70,
                                    "25": 162,
                                    "26": 205,
                                    "27": 73,
                                    "28": 7,
                                    "29": 90,
                                    "30": 117,
                                    "31": 177
                                },
                                "productHeaderImageRejected": false,
                                "lastPlaybackProgress": 0,
                                "isDynamicReplyButtonsMsg": false,
                                "isCarouselCard": false,
                                "parentMsgId": null,
                                "callSilenceReason": null,
                                "isVideoCall": false,
                                "callDuration": null,
                                "callCreator": null,
                                "callParticipants": null,
                                "isCallLink": null,
                                "callLinkToken": null,
                                "isMdHistoryMsg": false,
                                "stickerSentTs": 0,
                                "isAvatar": false,
                                "lastUpdateFromServerTs": 0,
                                "invokedBotWid": null,
                                "botTargetSenderJid": null,
                                "bizBotType": null,
                                "botResponseTargetId": null,
                                "botPluginType": null,
                                "botPluginReferenceIndex": null,
                                "botPluginSearchProvider": null,
                                "botPluginSearchUrl": null,
                                "botPluginSearchQuery": null,
                                "botPluginMaybeParent": false,
                                "botReelPluginThumbnailCdnUrl": null,
                                "botMessageDisclaimerText": null,
                                "botMsgBodyType": null,
                                "reportingTokenInfo": {
                                    "reportingTag": {},
                                    "version": -1
                                },
                                "requiresDirectConnection": false,
                                "bizContentPlaceholderType": null,
                                "hostedBizEncStateMismatch": false,
                                "senderOrRecipientAccountTypeHosted": false,
                                "placeholderCreatedWhenAccountIsHosted": false,
                                "galaxyFlowDisabled": false,
                                "links": []
                            },
                            "id": {
                                "fromMe": false,
                                "remote": "59175666929@c.us",
                                "id": "3A4E4A02958D133D7D41",
                                "_serialized": "false_59175666929@c.us_3A4E4A02958D133D7D41"
                            },
                            "ack": 0,
                            "hasMedia": false,
                            "body": "Que tal",
                            "type": "chat",
                            "timestamp": 1758337123,
                            "from": "59175666929@c.us",
                            "to": "59178505744@c.us",
                            "deviceType": "ios",
                            "isForwarded": false,
                            "forwardingScore": 0,
                            "isStatus": false,
                            "isStarred": false,
                            "broadcast": false,
                            "fromMe": false,
                            "hasQuotedMsg": false,
                            "hasReaction": false,
                            "vCards": [],
                            "mentionedIds": [],
                            "groupMentions": [],
                            "isGif": false,
                            "links": []
                        }
                    ],
                    "red_social": "redesFacebook",
                    "name": "Mary Fernandez",
                    "isGroup": false,
                    "unreadCount": 0,
                    "timestamp": 1758917314,
                    "archived": false,
                    "pinned": false,
                    "isMuted": false,
                    "muteExpiration": 0,
                    "lastMessage": {
                        "_data": {
                            "id": {
                                "fromMe": true,
                                "remote": "59173138212@c.us",
                                "id": "3EB0C9686BF9D4010530F0",
                                "_serialized": "true_59173138212@c.us_3EB0C9686BF9D4010530F0"
                            },
                            "viewed": false,
                            "body": "Lo siento, los precios actuales son los vigentes y fueron actualizados hoy 😊. No tenemos descuentos disponibles en este momento. Si deseas más información sobre nuestros productos, por favor indícamelo.",
                            "type": "chat",
                            "t": 1758917314,
                            "from": {
                                "server": "c.us",
                                "user": "59178505744",
                                "_serialized": "59178505744@c.us"
                            },
                            "to": {
                                "server": "c.us",
                                "user": "59173138212",
                                "_serialized": "59173138212@c.us"
                            },
                            "ack": 3,
                            "isNewMsg": true,
                            "star": false,
                            "kicNotified": false,
                            "isFromTemplate": false,
                            "pollInvalidated": false,
                            "isSentCagPollCreation": false,
                            "latestEditMsgKey": null,
                            "latestEditSenderTimestampMs": null,
                            "mentionedJidList": [],
                            "groupMentions": [],
                            "isEventCanceled": false,
                            "eventInvalidated": false,
                            "isVcardOverMmsDocument": false,
                            "isForwarded": false,
                            "isQuestion": false,
                            "questionReplyQuotedMessage": null,
                            "questionResponsesCount": 0,
                            "readQuestionResponsesCount": 0,
                            "labels": [],
                            "hasReaction": false,
                            "disappearingModeInitiator": "chat",
                            "disappearingModeTrigger": "chat_settings",
                            "disappearingModeInitiatedByMe": false,
                            "productHeaderImageRejected": false,
                            "lastPlaybackProgress": 0,
                            "isDynamicReplyButtonsMsg": false,
                            "isCarouselCard": false,
                            "parentMsgId": null,
                            "callSilenceReason": null,
                            "isVideoCall": false,
                            "callDuration": null,
                            "callCreator": null,
                            "callParticipants": null,
                            "isCallLink": null,
                            "callLinkToken": null,
                            "isMdHistoryMsg": false,
                            "stickerSentTs": 0,
                            "isAvatar": false,
                            "lastUpdateFromServerTs": 0,
                            "invokedBotWid": null,
                            "bizBotType": null,
                            "botResponseTargetId": null,
                            "botPluginType": null,
                            "botPluginReferenceIndex": null,
                            "botPluginSearchProvider": null,
                            "botPluginSearchUrl": null,
                            "botPluginSearchQuery": null,
                            "botPluginMaybeParent": false,
                            "botReelPluginThumbnailCdnUrl": null,
                            "botMessageDisclaimerText": null,
                            "botMsgBodyType": null,
                            "requiresDirectConnection": false,
                            "bizContentPlaceholderType": null,
                            "hostedBizEncStateMismatch": false,
                            "senderOrRecipientAccountTypeHosted": false,
                            "placeholderCreatedWhenAccountIsHosted": false,
                            "galaxyFlowDisabled": false,
                            "links": []
                        },
                        "id": {
                            "fromMe": true,
                            "remote": "59173138212@c.us",
                            "id": "3EB0C9686BF9D4010530F0",
                            "_serialized": "true_59173138212@c.us_3EB0C9686BF9D4010530F0"
                        },
                        "ack": 3,
                        "hasMedia": false,
                        "body": "Lo siento, los precios actuales son los vigentes y fueron actualizados hoy 😊. No tenemos descuentos disponibles en este momento. Si deseas más información sobre nuestros productos, por favor indícamelo.",
                        "type": "chat",
                        "timestamp": 1758917314,
                        "from": "59178505744@c.us",
                        "to": "59173138212@c.us",
                        "deviceType": "android",
                        "isForwarded": false,
                        "forwardingScore": 0,
                        "isStatus": false,
                        "isStarred": false,
                        "fromMe": true,
                        "hasQuotedMsg": false,
                        "hasReaction": false,
                        "vCards": [],
                        "mentionedIds": [],
                        "groupMentions": [],
                        "isGif": false,
                        "links": []
                    }
                },
                {
                    "id": {
                        "server": "c.us",
                        "user": "59169166780",
                        "_serialized": "59169166780@c.us"
                    },
                    "red_social": "redesInstagram",
                    "name": "Juan Perez",
                    "isGroup": false,
                    "unreadCount": 0,
                    "timestamp": 1758722137,
                    "archived": false,
                    "pinned": false,
                    "isMuted": false,
                    "muteExpiration": 0,
                    "lastMessage": {
                        "_data": {
                            "id": {
                                "fromMe": false,
                                "remote": "59169166780@c.us",
                                "id": "AC79371B688C046593E518B0AC48FB80",
                                "_serialized": "false_59169166780@c.us_AC79371B688C046593E518B0AC48FB80"
                            },
                            "viewed": false,
                            "body": "Le estoy dejando el pedido en recepción",
                            "type": "chat",
                            "t": 1758669489,
                            "notifyName": "",
                            "from": {
                                "server": "c.us",
                                "user": "59169166780",
                                "_serialized": "59169166780@c.us"
                            },
                            "to": {
                                "server": "c.us",
                                "user": "59178505744",
                                "_serialized": "59178505744@c.us"
                            },
                            "ack": 0,
                            "invis": false,
                            "star": false,
                            "kicNotified": false,
                            "isFromTemplate": false,
                            "pollInvalidated": false,
                            "isSentCagPollCreation": false,
                            "latestEditMsgKey": null,
                            "latestEditSenderTimestampMs": null,
                            "broadcast": false,
                            "mentionedJidList": [],
                            "groupMentions": [],
                            "isEventCanceled": false,
                            "eventInvalidated": false,
                            "isVcardOverMmsDocument": false,
                            "isForwarded": false,
                            "isQuestion": false,
                            "questionReplyQuotedMessage": null,
                            "questionResponsesCount": 0,
                            "readQuestionResponsesCount": 0,
                            "labels": [],
                            "hasReaction": false,
                            "viewMode": "VISIBLE",
                            "messageSecret": {
                                "0": 154,
                                "1": 122,
                                "2": 227,
                                "3": 98,
                                "4": 88,
                                "5": 154,
                                "6": 187,
                                "7": 212,
                                "8": 65,
                                "9": 82,
                                "10": 212,
                                "11": 49,
                                "12": 249,
                                "13": 151,
                                "14": 65,
                                "15": 142,
                                "16": 226,
                                "17": 131,
                                "18": 142,
                                "19": 251,
                                "20": 95,
                                "21": 14,
                                "22": 21,
                                "23": 85,
                                "24": 1,
                                "25": 94,
                                "26": 184,
                                "27": 240,
                                "28": 7,
                                "29": 12,
                                "30": 5,
                                "31": 189
                            },
                            "productHeaderImageRejected": false,
                            "lastPlaybackProgress": 0,
                            "isDynamicReplyButtonsMsg": false,
                            "isCarouselCard": false,
                            "parentMsgId": null,
                            "callSilenceReason": null,
                            "isVideoCall": false,
                            "callDuration": null,
                            "callCreator": null,
                            "callParticipants": null,
                            "isCallLink": null,
                            "callLinkToken": null,
                            "isMdHistoryMsg": false,
                            "stickerSentTs": 0,
                            "isAvatar": false,
                            "lastUpdateFromServerTs": 0,
                            "invokedBotWid": null,
                            "botTargetSenderJid": null,
                            "bizBotType": null,
                            "botResponseTargetId": null,
                            "botPluginType": null,
                            "botPluginReferenceIndex": null,
                            "botPluginSearchProvider": null,
                            "botPluginSearchUrl": null,
                            "botPluginSearchQuery": null,
                            "botPluginMaybeParent": false,
                            "botReelPluginThumbnailCdnUrl": null,
                            "botMessageDisclaimerText": null,
                            "botMsgBodyType": null,
                            "reportingTokenInfo": {
                                "reportingTag": {},
                                "version": -1
                            },
                            "requiresDirectConnection": false,
                            "bizContentPlaceholderType": null,
                            "hostedBizEncStateMismatch": false,
                            "senderOrRecipientAccountTypeHosted": false,
                            "placeholderCreatedWhenAccountIsHosted": false,
                            "galaxyFlowDisabled": false,
                            "links": []
                        },
                        "id": {
                            "fromMe": false,
                            "remote": "59169166780@c.us",
                            "id": "AC79371B688C046593E518B0AC48FB80",
                            "_serialized": "false_59169166780@c.us_AC79371B688C046593E518B0AC48FB80"
                        },
                        "ack": 0,
                        "hasMedia": false,
                        "body": "Le estoy dejando el pedido en recepción",
                        "type": "chat",
                        "timestamp": 1758669489,
                        "from": "59169166780@c.us",
                        "to": "59178505744@c.us",
                        "deviceType": "android",
                        "isForwarded": false,
                        "forwardingScore": 0,
                        "isStatus": false,
                        "isStarred": false,
                        "broadcast": false,
                        "fromMe": false,
                        "hasQuotedMsg": false,
                        "hasReaction": false,
                        "vCards": [],
                        "mentionedIds": [],
                        "groupMentions": [],
                        "isGif": false,
                        "links": []
                    }
                },
                {
                    "id": {
                        "server": "c.us",
                        "user": "59175395848",
                        "_serialized": "59175395848@c.us"
                    },
                    "red_social": "redesWhatsapp",
                    "name": "+591 75395848",
                    "isGroup": false,
                    "unreadCount": 0,
                    "timestamp": 1758553187,
                    "archived": false,
                    "pinned": false,
                    "isMuted": false,
                    "muteExpiration": 0,
                    "lastMessage": {
                        "_data": {
                            "id": {
                                "fromMe": false,
                                "remote": "59175395848@c.us",
                                "id": "3B76DFB77CAF13824984",
                                "_serialized": "false_59175395848@c.us_3B76DFB77CAF13824984"
                            },
                            "viewed": false,
                            "body": "https://testflight.apple.com/join/jtjxpEeG",
                            "type": "chat",
                            "subtype": "url",
                            "t": 1758553187,
                            "notifyName": "",
                            "from": {
                                "server": "c.us",
                                "user": "59175395848",
                                "_serialized": "59175395848@c.us"
                            },
                            "to": {
                                "server": "c.us",
                                "user": "59178505744",
                                "_serialized": "59178505744@c.us"
                            },
                            "ack": 0,
                            "invis": false,
                            "star": false,
                            "kicNotified": false,
                            "isFromTemplate": false,
                            "matchedText": "https://testflight.apple.com/join/jtjxpEeG",
                            "thumbnail": "",
                            "richPreviewType": 0,
                            "faviconMMSMetadata": null,
                            "title": "TestFlight - Apple",
                            "description": "Using TestFlight is a great way to help developers test beta versions of their apps.",
                            "pollInvalidated": false,
                            "isSentCagPollCreation": false,
                            "latestEditMsgKey": null,
                            "latestEditSenderTimestampMs": null,
                            "broadcast": false,
                            "mentionedJidList": [],
                            "groupMentions": [],
                            "isEventCanceled": false,
                            "eventInvalidated": false,
                            "isVcardOverMmsDocument": false,
                            "font": 0,
                            "isForwarded": false,
                            "isQuestion": false,
                            "questionReplyQuotedMessage": null,
                            "questionResponsesCount": 0,
                            "readQuestionResponsesCount": 0,
                            "labels": [],
                            "hasReaction": false,
                            "viewMode": "VISIBLE",
                            "messageSecret": {
                                "0": 138,
                                "1": 80,
                                "2": 31,
                                "3": 242,
                                "4": 201,
                                "5": 144,
                                "6": 19,
                                "7": 61,
                                "8": 185,
                                "9": 243,
                                "10": 199,
                                "11": 250,
                                "12": 184,
                                "13": 2,
                                "14": 54,
                                "15": 144,
                                "16": 180,
                                "17": 159,
                                "18": 234,
                                "19": 21,
                                "20": 139,
                                "21": 79,
                                "22": 214,
                                "23": 151,
                                "24": 74,
                                "25": 194,
                                "26": 233,
                                "27": 236,
                                "28": 130,
                                "29": 240,
                                "30": 111,
                                "31": 135
                            },
                            "inviteGrpType": "DEFAULT",
                            "productHeaderImageRejected": false,
                            "lastPlaybackProgress": 0,
                            "isDynamicReplyButtonsMsg": false,
                            "isCarouselCard": false,
                            "parentMsgId": null,
                            "callSilenceReason": null,
                            "isVideoCall": false,
                            "callDuration": null,
                            "callCreator": null,
                            "callParticipants": null,
                            "isCallLink": null,
                            "callLinkToken": null,
                            "isMdHistoryMsg": false,
                            "stickerSentTs": 0,
                            "isAvatar": false,
                            "lastUpdateFromServerTs": 0,
                            "invokedBotWid": null,
                            "botTargetSenderJid": null,
                            "bizBotType": null,
                            "botResponseTargetId": null,
                            "botPluginType": null,
                            "botPluginReferenceIndex": null,
                            "botPluginSearchProvider": null,
                            "botPluginSearchUrl": null,
                            "botPluginSearchQuery": null,
                            "botPluginMaybeParent": false,
                            "botReelPluginThumbnailCdnUrl": null,
                            "botMessageDisclaimerText": null,
                            "botMsgBodyType": null,
                            "reportingTokenInfo": {
                                "reportingTag": {},
                                "version": -1
                            },
                            "requiresDirectConnection": false,
                            "bizContentPlaceholderType": null,
                            "hostedBizEncStateMismatch": false,
                            "senderOrRecipientAccountTypeHosted": false,
                            "placeholderCreatedWhenAccountIsHosted": false,
                            "galaxyFlowDisabled": false,
                            "links": [
                                {
                                    "link": "https://testflight.apple.com/join/jtjxpEeG",
                                    "isSuspicious": false
                                }
                            ]
                        },
                        "id": {
                            "fromMe": false,
                            "remote": "59175395848@c.us",
                            "id": "3B76DFB77CAF13824984",
                            "_serialized": "false_59175395848@c.us_3B76DFB77CAF13824984"
                        },
                        "ack": 0,
                        "hasMedia": false,
                        "body": "Buenas buenas",
                        "type": "chat",
                        "timestamp": 1758553187,
                        "from": "59175395848@c.us",
                        "to": "59178505744@c.us",
                        "deviceType": "web",
                        "isForwarded": false,
                        "forwardingScore": 0,
                        "isStatus": false,
                        "isStarred": false,
                        "broadcast": false,
                        "fromMe": false,
                        "hasQuotedMsg": false,
                        "hasReaction": false,
                        "vCards": [],
                        "mentionedIds": [],
                        "groupMentions": [],
                        "isGif": false,
                        "title": "TestFlight - Apple",
                        "description": "Using TestFlight is a great way to help developers test beta versions of their apps.",
                        "links": [
                            {
                                "link": "https://testflight.apple.com/join/jtjxpEeG",
                                "isSuspicious": false
                            }
                        ]
                    }
                },




            ]
        };
    }

    componentDidMount() {
        MDL.rolesPermisos.getPermisoAsync({ url: "/social_media/mensajes", permiso: "ver" }).then((permit) => {
            if (!permit) {
                SNavigation.goBack();
                return;
            }
        })
    }

    render() {
        return (
            <SPage title={'Social Media Mensajes'}  >
                {/* <MenuPages path={"/social_media/"} >
                </MenuPages> */}
                <SView col={"xs-12"} row height>
                    <SView width={250} backgroundColor={STheme.color.background} height>
                        <MensajesLista data={this.state.data} />
                    </SView>
                    <SView width={2} backgroundColor={STheme.color.card} />
                    <SView flex backgroundColor={STheme.color.background} height >
                        <MensajeDetalle data={this.state.data?.[0]} />
                    </SView>
                    <SView width={2} backgroundColor={STheme.color.card} />
                    <SView width={200} backgroundColor={STheme.color.background} >
                        <MensajeContacto data={this.state.data?.[0]} />
                    </SView>
                </SView>

            </SPage>
        );
    }
}
const initStates = (state) => {
    return { state }
};
export default connect(initStates)(mensajes);